In [6]:
pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.3.4-py3-none-any.whl (35 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.6.3)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from snscrape) (4.9.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.7/dist-packages (from snscrape) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.7/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.3.4

In [8]:
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = "(from:narendramodi) until:2022-01-01 since:2015-01-01"
tweets = []
limit = 500


for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    
    # print(vars(tweet))
    # break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.username, tweet.content])
        
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet'])
print(df)


df

                         Date          User  \
0   2021-12-31 14:07:47+00:00  narendramodi
1   2021-12-30 13:40:18+00:00  narendramodi
2   2021-12-30 13:40:12+00:00  narendramodi
3   2021-12-30 13:40:02+00:00  narendramodi
4   2021-12-30 13:39:17+00:00  narendramodi
..                        ...           ...
495 2021-11-01 15:47:07+00:00  narendramodi
496 2021-11-01 15:33:54+00:00  narendramodi
497 2021-11-01 15:24:32+00:00  narendramodi
498 2021-11-01 14:17:41+00:00  narendramodi
499 2021-11-01 11:15:24+00:00  narendramodi

                                                 Tweet
0    नव वर्ष, 2022 का पहला दिन देश के अन्नदाताओं को...
1    देश में दशकों तक बड़ी योजनाओं की बात होने पर य...
2    देवभूमि उत्तराखंड के लोगों की सेवा करना, देवी-...
3    उत्तराखंड से कितनी ही नदियां निकलती हैं, लेकिन...
4    इस दशक को उत्तराखंड का दशक बनाने के लिए तेज गत...
..                                                 ...
495  The @COP26 Summit offers a wonderful opportuni...
496  Addressing the @COP26 Summit in Glasgow. https...
497  Will be addressing the @COP26 Summit shortly, ...
498  I thank my dear friend @ScottMorrisonMP for Au...
499  Heartiest felicitations to @kishida230 for vic...

[500 rows x 3 columns]

,Date,User,Tweet
0,2021-12-31 14:07:47+00:00,narendramodi,"नव वर्ष, 2022 का पहला दिन देश के अन्नदाताओं को..."
1,2021-12-30 13:40:18+00:00,narendramodi,देश में दशकों तक बड़ी योजनाओं की बात होने पर य...
2,2021-12-30 13:40:12+00:00,narendramodi,"देवभूमि उत्तराखंड के लोगों की सेवा करना, देवी-..."
3,2021-12-30 13:40:02+00:00,narendramodi,"उत्तराखंड से कितनी ही नदियां निकलती हैं, लेकिन..."
4,2021-12-30 13:39:17+00:00,narendramodi,इस दशक को उत्तराखंड का दशक बनाने के लिए तेज गत...
...,...,...,...
495,2021-11-01 15:47:07+00:00,narendramodi,The @COP26 Summit offers a wonderful opportuni...
496,2021-11-01 15:33:54+00:00,narendramodi,Addressing the @COP26 Summit in Glasgow. https...
497,2021-11-01 15:24:32+00:00,narendramodi,"Will be addressing the @COP26 Summit shortly, ..."
498,2021-11-01 14:17:41+00:00,narendramodi,I thank my dear friend @ScottMorrisonMP for Au...
499,2021-11-01 11:15:24+00:00,narendramodi,Heartiest felicitations to @kishida230 for vic...